### PR TITLE
(Redo of) Fix #283: Visits to alerts.php shouldn't mark all read

### LINKED ISSUE #283: Visits to alerts.php shouldn't mark all alerts as read

### PR DESCRIPTION
**Pull request by lairdshaw**
Resolves #283

Obsoletes #284

### CODE REVIEW

**Comment by lairdshaw** [comment]
As usual, in the absence of objections, I'll merge this in a week or so. Then, I suggest that we bump this plugin's version from 2.0.4 to 2.1.0.

**Comment by Eldenroot** [comment]
For 2.1.0 - tickets should be checked, maybe there are few more small bugs. Invalid tickets close, I had added few comments in last couple of weeks

**Comment by lairdshaw** [comment]
> For 2.1.0 - tickets should be checked, maybe there are few more small bugs. Invalid tickets close, I had added few comments in last couple of weeks

In the meantime, I've created a little PR (#310) to bump the version to `2.1.0-dev`, just so we avoid confusion given that quite a few changes have already been made, and this repo is the main place from which people download the plugin for production sites. Unless there are any objections, I'll merge it in the next day or two.

**Comment by lairdshaw** [comment]
> I had added few comments in last couple of weeks

I'd responded in some of them. Am awaiting your response in turn in #145, #188, and #191.

**Pull request merged**
