### PR TITLE
Fix #312: Alerts count in title and header icon not updating

### LINKED ISSUE #312: Alerts count in title and header icon doesn't update when an individual alert is marked read / deleted via the modal

### PR DESCRIPTION
**Pull request by lairdshaw**
...when an individual alert is marked read / deleted via the modal.

Resolves #312

### CODE REVIEW

**Comment by Eldenroot** [comment]
Good, thank you.

**Comment by Eldenroot** [comment]
OK, after some testing it is not working correctly in all cases. No alerts to display, but it shows (1). Before the applying this patch if was broken also in all cases, now it happens only sometimes.

image

**Comment by Eldenroot** [comment]
Nope. It happens when you sometimes open a board... alert is not displayed

**Comment by lairdshaw** [comment]
> Nope. It happens when you sometimes open a board... alert is not displayed

I can't see how this PR could be causing that. The new functionality that it implements is only called (via Javascript) when clicking in the modal on one of the delete/mark-read icons beside an individual alert. Simply opening a page and then opening the modal (without clicking on anything in the modal) shouldn't result in any of this new functionality being called.

If you can find a way to reproduce it, and let us know, that would be very helpful.

**Comment by Eldenroot** [comment]
Well, it happens only sometime.

All alerts are marked as read... counter shows "Alerts (0)"... but sometimes it shows "alerts (1)" but if you open the modal box or alert.phh in UCP there is no alerts... you have to click on mark all read or delete alerts to make it working... before this PR it was broken completely, this is a good step

**Pull request merged**
