### PR TITLE
Fix #193 Change myalerts_addAlert_pm() to use the PMDataHandler hook

### LINKED ISSUE #193: Change private_do_send_end hook to datahandler_pm_insert or similar
Hi Euan, I know you might be busier on something else as I am busy too, but here's a possible enhancement for the next minor update. private_do_send_end hook which is used to generate the PM alert should be changed with datahandler_pm_insert or something similar found in the pmhandler (reported by Brenda [here](http://www.mybboost.com/thread-myalerts-pm-support-password-empty)). Otherwise, third party plugins sending PMs will not generate an alert.

This is not top priority, and I have not had a look at MyAlerts current implementation so I don't know how hard would it be to change the logic, but I'd just leave it here. If only I got some spare time I would open a PR but unfortunately I have not.

### PR DESCRIPTION
**Pull request by dvz**
#193

depends on mybb/mybb#2870

### CODE REVIEW

**Comment by euantorano** [comment]
Once that PR gets merged, I'll merge this.

**Comment by dvz** [comment]
It also might be a good idea to wait until a MyBB version containing those changes is released since people are often referred to `master` here to download the plugin, unless you want to return to using Releases (and bumping version numbers).

**Comment by euantorano** [comment]
I probably should start using version numbers again really...

**Comment by WildcardSearch** [comment]
Oh, please do...It goes against my anal retentive nature! 😛

**Comment by euantorano** [comment]
I also need to set up a `feature` branch and put some more effort into the plugin in general. I might end up moving it back under my account.

**Comment by WildcardSearch** [comment]
That sounds great. I certainly understand being stretched too thin.

**Pull request merged**
