### PR TITLE
Fix #283: Visits to alerts.php shouldn't mark all alerts as read

### LINKED ISSUE #283: Visits to alerts.php shouldn't mark all alerts as read

### PR DESCRIPTION
**Pull request by lairdshaw**
Resolves #283

### CODE REVIEW

**Comment by lairdshaw** [comment]
In the course of the fix, this PR also disables some functionality that wasn't working properly: the in-page updating of the alert listing (either via a manual trigger or automatically on an interval). It doesn't remove that functionality though, because it would be possible to fix it with some work - I just haven't put that work in. The main problems that need solving are:

1. The update prepends alerts to the list, even when there are no new alerts (so, it creates duplicates).
2. The update doesn't strictly get new (or even unread) alerts; it just gets the most recent alerts - again, creating duplicates.

**Comment by lairdshaw** [comment]
> This wouod be good to cover by another PR amd create a ticket to follow

Agreed. Please feel free to create the ticket; otherwise, I'll get onto it at some (indeterminate!) point after completing some other tasks.

**Comment by Eldenroot** [comment]
This one still needs some love :)

**Comment by lairdshaw** [comment]
> This one still needs some love :)

Yes. Once my other existing PRs have been merged, I'll implement a proper fix for the functionality that this PR currently simply disables.

**Comment by lairdshaw** [comment]
> > This one still needs some love :)
> 
> Yes. Once my other existing PRs have been merged, I'll implement a proper fix for the functionality that this PR currently simply disables.

Here's that proper fix: #305. Please feel free to test and provide feedback.

**Comment by Eldenroot** [comment]
Should be fixed. Thx!

**Comment by lairdshaw** [comment]
Obsoleted by #309. I created that new PR rather than resolving conflicts in this one generated by the merge of #305.

**Pull request closed without merging**
